.catalog:
  name: "Calico"
  version: "v0.23.0"
  questions:
  - variable: EMBEDDED_BACKUPS
    label: Enable Backups
    description: "Periodically backup state to /var/etcd/backups. Mount network storage here on all hosts before continuing"
    required: true
    default: true
    type: boolean
  - variable: BACKUP_PERIOD
    label: Backup Creation Period
    description: "Create a backup after this amount of time passes. Must conform to duration format"
    required: true
    default: 15m0s
    type: string
  - variable: BACKUP_RETENTION
    label: Backup Retention Period
    description: "Expire a backup after this amount of time passes. Must conform to duration format"
    required: true
    default: 24h
    type: string


ipsec:
  network_driver:
    name: Calico
    default_network:
      name: calico
      dns:
      - 169.254.169.250
      dns_search:
      - rancher.internal
    cni_config:
      '10-rancher-calico.conf':
        name: rancher-calico-network
        type: calico
        etcd_authority: etcd:2379
        log_level: info
        ipam:
          type: calico-ipam

etcd:
    retain_ip: true
    scale_policy:
      increment: 1
      max: 3
      min: 1
    health_check:
      port: 2378
      request_line: GET /health HTTP/1.0
      interval: 5000
      response_timeout: 3000
      unhealthy_threshold: 3
      healthy_threshold: 2
      recreate_on_quorum_strategy_config:
          quorum: 2
      strategy: recreateOnQuorum
