.catalog:
  name: "Rancher Flat Networking"
  version: "0.0.4"
  questions:
    - variable: "DOCKER_BRIDGE"
      label: "Docker Bridge"
      description: "Name of Docker Bridge. Default is `docker0`"
      type: "string"
      default: "mpbr0"
      required: true
    - variable: MTU
      label: "MTU for the network"
      description: "Adjust the MTU for the network, according to your needs. Ex: GCE(1460), AWS(1500), etc"
      required: true
      default: 1500
      type: int
    - variable: "SUBNET"
      label: "Subnet"
      description: "The subnet to use for the managed IPSEC network."
      type: "string"
      default: "10.42.0.0/16"
      required: true
    - variable: "RANCHER_DEBUG"
      label: "Enable Debug Logs"
      description: "This will enable very verbose debug logs."
      type: "boolean"
      default: "false"
      required: true

flat:
  network_driver:
    name: Rancher Flat Networking
    default_network:
      name: flat
      host_ports: true
      dns:
      - 169.254.169.250
      dns_search:
      - rancher.internal
    cni_config:
      '10-rancher-flat.conf':
        name: rancher-cni-network
        type: rancher-bridge
        bridge: $DOCKER_BRIDGE
        bridgeSubnet: $SUBNET
        isDefaultGateway: true
        hostNat: true
        hairpinMode: true
        mtu: ${MTU}
        ipam:
          type: host-local
          subnet: '172.25.101.0/24'
